SELECT * 
FROM customer_data


--==================================================================================
-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender ,SUM(purchase_amount) AS REVENUE
FROM customer_data
GROUP BY gender

--==================================================================================
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount
FROM customer_data
WHERE discount_applied='Yes' AND purchase_amount >= (SELECT AVG (purchase_amount) FROM CUSTOMER_DATA)
--==================================================================================
-- Q3. Which are the top 5 products with the highest average review rating?
SELECT  TOP 5
item_purchased, ROUND(AVG( review_rating),2) AS AVERAGE_PRODUCT_RATING
FROM customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating)DESC

--==================================================================================
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
shipping_type,
AVG(purchase_amount)
FROM customer_data
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type
--===================================================================================
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
--====================================================================================
SELECT  subscription_status,
COUNT (customer_id) AS TOTAL_CUSTOMER,
ROUND(AVG(purchase_amount),2) AS AVG_SPEND,
ROUND(SUM(purchase_amount),2) AS TOTAL_REVENUE
FROM customer_data
GROUP BY subscription_status
ORDER BY TOTAL_REVENUE,AVG_SPEND DESC
--===================================================================================================
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
--====================================================================================================
SELECT  TOP 5
item_purchased,
ROUND(100*sum(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END )/COUNT(*),2) AS  DISCOUNT_RATE
FROM customer_data
GROUP BY item_purchased
ORDER BY DISCOUNT_RATE
--===============================================================================================
-- Q7. Segment customers into New, Returning, and Loyal based on their total number of
--previous purchases, and show the count of each segment.
--================================================================================================
WITH  customer_type AS (
SELECT customer_id,previous_purchases,
CASE	
	WHEN previous_purchases=1 THEN 'NEW'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
	ELSE 'LOYAL'
	END AS customer_segment
FROM customer_data
)
SELECT customer_segment,COUNT(*) AS 'number of customer'
FROM customer_type
GROUP BY customer_segment










-- Q8. What are the top 3 most purchased products within each category?
WITH item_count AS (
SELECT 
category,
item_purchased,
COUNT(customer_id) AS TOTAL_ORDERS,
ROW_NUMBER()  OVER (PARTITION BY category ORDER BY COUNT(customer_id)DESC) AS item_rank
FROM customer_data
GROUP BY category,item_purchased
)
SELECT item_rank,category,item_purchased,total_orders
FROM item_count
WHERE item_rank<=3
--=====================================================================================================
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
--=====================================================================================================
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer_data
WHERE previous_purchases>5
GROUP BY subscription_status
--======================================================================================================
--Q10. What is the revenue contribution of each age group?
SELECT 
age,
SUM(purchase_amount) AS TOTAL_REVENUE
FROM customer_data
GROUP BY age
ORDER BY TOTAL_REVENUE DESC